[package]
name = "sqlglotrs"
version = "0.3.0"
edition = "2021"
license = "MIT"

[lib]
name = "sqlglotrs"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = "fat"

[dependencies]
pyo3 = "0.22.6"
ahash = "0.8.11"
